# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftDemoNY' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftDemoNY
  pod 'NYAlertViewController'
  
  target 'SwiftDemoNYTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftDemoNYUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
